# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ScanOCR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TesseractOCRiOS', :git => 'git://github.com/parallaxe/Tesseract-OCR-iOS.git', :branch => 'macos-support'

  # Pods for ScanOCR

end
